function normalizeManifestJson(manifestJson) {
    return manifestJson.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
}

function sanitizeImportSpecifier(specifier) {
    return specifier
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\r\n/g, '')
        .replace(/[\r\n]/g, '');
}

export function renderRouterModule(opts) {
    if (!opts || typeof opts !== 'object') {
        throw new Error('renderRouterModule(opts) requires an options object');
    }

    const { manifestJson, runtimeImport, coreImport } = opts;

    if (typeof manifestJson !== 'string' || manifestJson.length === 0) {
        throw new Error('renderRouterModule(opts) requires opts.manifestJson string');
    }
    if (typeof runtimeImport !== 'string' || runtimeImport.length === 0) {
        throw new Error('renderRouterModule(opts) requires opts.runtimeImport string');
    }
    if (typeof coreImport !== 'string' || coreImport.length === 0) {
        throw new Error('renderRouterModule(opts) requires opts.coreImport string');
    }

    const manifest = normalizeManifestJson(manifestJson);
    const runtimeSpec = sanitizeImportSpecifier(runtimeImport);
    const coreSpec = sanitizeImportSpecifier(coreImport);

    const lines = [
        `import { hydrate as __zenithHydrate } from '${runtimeSpec}';`,
        `import { zenOnMount as __zenithOnMount } from '${coreSpec}';`,
        '',
        'void __zenithHydrate;',
        'void __zenithOnMount;',
        '',
        `const __ZENITH_MANIFEST__ = ${manifest};`,
        '',
        'let activeCleanup = null;',
        'let navigationToken = 0;',
        '',
        'function splitPath(path) {',
        "  return path.split('/').filter(Boolean);",
        '}',
        '',
        'function normalizeCatchAll(segments) {',
        "  return segments.filter(Boolean).join('/');",
        '}',
        '',
        'function requiresServerReload(route) {',
        '  const routes = __ZENITH_MANIFEST__.server_routes || __ZENITH_MANIFEST__.serverRoutes || [];',
        "  return Array.isArray(routes) && routes.includes(route);",
        '}',
        '',
        'const __ZENITH_ROUTE_POLICY_KEY = "__zenith_route_protection_policy";',
        'const __ZENITH_ROUTE_EVENT_KEY = "__zenith_route_event_listeners";',
        'const __ZENITH_ROUTE_EVENT_NAMES = ["guard:start", "guard:end", "route-check:start", "route-check:end", "route-check:error", "route:deny", "route:redirect"];',
        '',
        'function __zenithEnsureRouteProtectionState() {',
        '  const scope = typeof globalThis === "object" && globalThis ? globalThis : window;',
        '  let policy = scope[__ZENITH_ROUTE_POLICY_KEY];',
        '  if (!policy || typeof policy !== "object") {',
        '    policy = {};',
        '    scope[__ZENITH_ROUTE_POLICY_KEY] = policy;',
        '  }',
        '  let listeners = scope[__ZENITH_ROUTE_EVENT_KEY];',
        '  if (!listeners || typeof listeners !== "object") {',
        '    listeners = Object.create(null);',
        '    scope[__ZENITH_ROUTE_EVENT_KEY] = listeners;',
        '  }',
        '  for (let i = 0; i < __ZENITH_ROUTE_EVENT_NAMES.length; i++) {',
        '    const name = __ZENITH_ROUTE_EVENT_NAMES[i];',
        '    if (!(listeners[name] instanceof Set)) {',
        '      listeners[name] = new Set();',
        '    }',
        '  }',
        '  return { policy, listeners };',
        '}',
        '',
        'function __zenithGetRouteProtectionPolicy() {',
        '  return __zenithEnsureRouteProtectionState().policy;',
        '}',
        '',
        'function __zenithDispatchRouteEvent(eventName, payload) {',
        '  const listeners = __zenithEnsureRouteProtectionState().listeners[eventName];',
        '  if (!(listeners instanceof Set)) return;',
        '  for (const handler of listeners) {',
        '    try {',
        '      handler(payload);',
        '    } catch (error) {',
        '      console.error("[Zenith Router] route event handler failed", error);',
        '    }',
        '  }',
        '}',
        '',
        'function segmentWeight(segment) {',
        '  if (!segment) return 0;',
        "  if (segment.startsWith('*')) return 1;",
        "  if (segment.startsWith(':')) return 2;",
        '  return 3;',
        '}',
        '',
        'function routeClass(segments) {',
        '  let hasParam = false;',
        '  let hasCatchAll = false;',
        '  for (let i = 0; i < segments.length; i++) {',
        '    const segment = segments[i];',
        "    if (segment.startsWith('*')) {",
        '      hasCatchAll = true;',
        "    } else if (segment.startsWith(':')) {",
        '      hasParam = true;',
        '    }',
        '  }',
        '  if (!hasParam && !hasCatchAll) return 3;',
        '  if (hasCatchAll) return 1;',
        '  return 2;',
        '}',
        '',
        'function compareRouteSpecificity(a, b) {',
        "  if (a === '/' && b !== '/') return -1;",
        "  if (b === '/' && a !== '/') return 1;",
        '  const aSegs = splitPath(a);',
        '  const bSegs = splitPath(b);',
        '  const aClass = routeClass(aSegs);',
        '  const bClass = routeClass(bSegs);',
        '  if (aClass !== bClass) {',
        '    return bClass - aClass;',
        '  }',
        '  const max = Math.min(aSegs.length, bSegs.length);',
        '  for (let i = 0; i < max; i++) {',
        '    const aWeight = segmentWeight(aSegs[i]);',
        '    const bWeight = segmentWeight(bSegs[i]);',
        '    if (aWeight !== bWeight) {',
        '      return bWeight - aWeight;',
        '    }',
        '  }',
        '  if (aSegs.length !== bSegs.length) {',
        '    return bSegs.length - aSegs.length;',
        '  }',
        '  return a.localeCompare(b);',
        '}',
        '',
        'function resolveRoute(pathname) {',
        '  if (__ZENITH_MANIFEST__.chunks[pathname]) {',
        '    return { route: pathname, params: {} };',
        '  }',
        '',
        '  const pathnameSegments = splitPath(pathname);',
        '  const routes = Object.keys(__ZENITH_MANIFEST__.chunks).sort(compareRouteSpecificity);',
        '',
        '  for (let i = 0; i < routes.length; i++) {',
        '    const route = routes[i];',
        '    const routeSegments = splitPath(route);',
        '    const params = Object.create(null);',
        '    let routeIndex = 0;',
        '    let pathIndex = 0;',
        '    let matched = true;',
        '',
        '    while (routeIndex < routeSegments.length) {',
        '      const routeSegment = routeSegments[routeIndex];',
        "      if (routeSegment.startsWith('*')) {",
        "        const optionalCatchAll = routeSegment.endsWith('?');",
        "        const key = optionalCatchAll ? routeSegment.slice(1, -1) : routeSegment.slice(1);",
        '        if (routeIndex !== routeSegments.length - 1) {',
        '          matched = false;',
        '          break;',
        '        }',
        '        const rest = pathnameSegments.slice(pathIndex);',
        '        const rootRequiredCatchAll = !optionalCatchAll && routeSegments.length === 1;',
        '        if (rest.length === 0 && !optionalCatchAll && !rootRequiredCatchAll) {',
        '          matched = false;',
        '          break;',
        '        }',
        '        params[key] = normalizeCatchAll(rest);',
        '        pathIndex = pathnameSegments.length;',
        '        routeIndex = routeSegments.length;',
        '        continue;',
        '      }',
        '      if (pathIndex >= pathnameSegments.length) {',
        '        matched = false;',
        '        break;',
        '      }',
        '      const pathnameSegment = pathnameSegments[pathIndex];',
        "      if (routeSegment.startsWith(':')) {",
        '        params[routeSegment.slice(1)] = pathnameSegment;',
        '      } else if (routeSegment !== pathnameSegment) {',
        '        matched = false;',
        '        break;',
        '      }',
        '      routeIndex += 1;',
        '      pathIndex += 1;',
        '    }',
        '',
        '    if (matched && routeIndex === routeSegments.length && pathIndex === pathnameSegments.length) {',
        '      return { route, params: { ...params } };',
        '    }',
        '  }',
        '',
        '  return null;',
        '}',
        '',
        'function teardownRuntime() {',
        "  if (typeof activeCleanup === 'function') {",
        '    activeCleanup();',
        '    activeCleanup = null;',
        '  }',
        '}',
        '',
        'async function mountRoute(route, params, token) {',
        '  if (token !== navigationToken) return;',
        '  teardownRuntime();',
        '  if (token !== navigationToken) return;',
        '',
        '  const pageModule = await import(__ZENITH_MANIFEST__.chunks[route]);',
        '  if (token !== navigationToken) return;',
        '',
        '  const mountFn = pageModule.__zenith_mount || pageModule.default;',
        "  if (typeof mountFn === 'function') {",
        '    const cleanup = mountFn(document, params);',
        "    activeCleanup = typeof cleanup === 'function' ? cleanup : null;",
        '  }',
        '}',
        '',
        'async function navigate(pathname, url) {',
        '  const next = resolveRoute(pathname);',
        '  if (!next) return false;',
        '',
        '  navigationToken += 1;',
        '  const token = navigationToken;',
        '',
        '  await mountRoute(next.route, next.params, token);',
        '  if (token !== navigationToken) return false;',
        "  if (typeof window.scrollTo === 'function') {",
        '    window.scrollTo(0, 0);',
        '  }',
        '  return true;',
        '}',
        '',
        'function handleNavigationFailure(error, url) {',
        "  console.error('[Zenith Router] navigation failed', error);",
        "  if (url && typeof url.href === 'string') {",
        '    window.location.assign(url.href);',
        '  }',
        '}',
        '',
        'function isInternalLink(anchor) {',
        "  if (!anchor || anchor.target || anchor.hasAttribute('download')) return false;",
        "  const href = anchor.getAttribute('href');",
        "  if (!href || href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('tel:')) return false;",
        '  const url = new URL(anchor.href, window.location.href);',
        '  return url.origin === window.location.origin;',
        '}',
        '',
        'function start() {',
        "  if (typeof history === 'object' && history && 'scrollRestoration' in history) {",
        "    history.scrollRestoration = 'manual';",
        '  }',
        '',
        "  document.addEventListener('click', function (event) {",
        "    if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;",
        "    const target = event.target && event.target.closest ? event.target.closest('a[data-zen-link]') : null;",
        '    if (!isInternalLink(target)) return;',
        '',
        '    const url = new URL(target.href, window.location.href);',
        '    const hashOnlyNavigation =',
        '      url.hash &&',
        '      url.pathname === window.location.pathname &&',
        '      url.search === window.location.search;',
        '    if (hashOnlyNavigation) return;',
        '    const nextPath = url.pathname;',
        "    if (nextPath === window.location.pathname && url.search === window.location.search && url.hash === window.location.hash) return;",
        '    const resolved = resolveRoute(nextPath);',
        '    if (!resolved) return;',
        '',
        '    function evaluateServerGuard(path, targetUrl, onSuccess) {',
        '      if (!requiresServerReload(resolved.route)) {',
        '        onSuccess();',
        '        return;',
        '      }',
        '      __zenithDispatchRouteEvent("route-check:start", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route });',
        '      fetch("/__zenith/route-check?path=" + encodeURIComponent(path), { headers: { "x-zenith-route-check": "1" }, credentials: "include" }).then(function(res) {',
        '        return res.json().then(function(data) {',
        '          if (!res.ok) throw new Error("route-check failed");',
        '          return data;',
        '        });',
        '      }).then(function(checkResult) {',
        '        if (checkResult && checkResult.result) {',
        '          const result = checkResult.result;',
        '          __zenithDispatchRouteEvent("route-check:end", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, result });',
        '          const policy = __zenithGetRouteProtectionPolicy();',
        '          if (result.kind === "redirect") {',
        '             __zenithDispatchRouteEvent("route:redirect", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, result });',
        '             window.location.assign(result.location || "/");',
        '             return;',
        '          }',
        '          if (result.kind === "deny") {',
        '             __zenithDispatchRouteEvent("route:deny", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, result });',
        '             console.warn("[Zenith] Route denied:", result.message);',
        '             if (result.status === 401 && policy.deny401RedirectToLogin !== false) {',
        '                 const loginPath = policy.defaultLoginPath || "/login";',
        '                 window.location.assign(loginPath + "?next=" + encodeURIComponent(targetUrl.pathname + targetUrl.search + targetUrl.hash));',
        '                 return;',
        '             }',
        '             if (result.status === 403 && (policy.onDeny === "navigate" || policy.onDeny === "render403" || policy.forbiddenPath)) {',
        '                 window.location.assign(policy.forbiddenPath || "/403");',
        '                 return;',
        '             }',
        '             if (policy.onDeny === "redirect") {',
        '                 window.location.assign(policy.defaultLoginPath || "/login");',
        '                 return;',
        '             }',
        '             if (typeof policy.onDeny === "function") {',
        '                 policy.onDeny(result);',
        '                 return;',
        '             }',
        '             // Restore history state if this was a popstate (to prevent URL bar flash)',
        '             if (window._zenith_is_popstate_nav) {',
        '                 history.pushState(null, "", window.location.href);',
        '             }',
        '             return; // No-flash block',
        '          }',
        '          onSuccess();',
        '        } else {',
        '          window.location.assign(targetUrl.href);',
        '        }',
        '      }).catch(function(e) {',
        '          __zenithDispatchRouteEvent("route-check:error", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, error: e });',
        '          console.error("[Zenith Router] fallback route-check failed", e);',
        '          window.location.assign(targetUrl.href);',
        '      });',
        '    }',
        '',
        '    evaluateServerGuard(nextPath, url, function() {',
        '      try {',
        '        event.preventDefault();',
        '        navigate(nextPath, url).catch(function (error) {',
        "          console.error('[Zenith Router] click navigation failed', error);",
        '          window.location.assign(url.href);',
        '        });',
        '      } catch (e) {',
        "        console.error('[Zenith Router] click navigation generated sync error', e);",
        '        window.location.assign(url.href);',
        '      }',
        '    });',
        '  });',
        '',
        "  window.addEventListener('popstate', function (event) {",
        '    const url = new URL(window.location.href);',
        '    const nextPath = url.pathname;',
        '    const resolved = resolveRoute(nextPath);',
        '    if (!resolved) return;',
        '',
        '    window._zenith_is_popstate_nav = true;',
        '    // Re-use evaluateServerGuard but attach different success handler since popstate already changes URL',
        '    function popstateEvaluateGuard(path, targetUrl, onSuccess) {',
        '      if (!requiresServerReload(resolved.route)) {',
        '        onSuccess();',
        '        return;',
        '      }',
        '      __zenithDispatchRouteEvent("route-check:start", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route });',
        '      fetch("/__zenith/route-check?path=" + encodeURIComponent(path), { headers: { "x-zenith-route-check": "1" }, credentials: "include" }).then(function(res) {',
        '        return res.json().then(function(data) {',
        '          if (!res.ok) throw new Error("route-check failed");',
        '          return data;',
        '        });',
        '      }).then(function(checkResult) {',
        '        if (checkResult && checkResult.result) {',
        '          const result = checkResult.result;',
        '          __zenithDispatchRouteEvent("route-check:end", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, result });',
        '          const policy = __zenithGetRouteProtectionPolicy();',
        '          if (result.kind === "redirect") {',
        '             __zenithDispatchRouteEvent("route:redirect", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, result });',
        '             window._zenith_is_popstate_nav = false;',
        '             window.location.assign(result.location || "/");',
        '             return;',
        '          }',
        '          if (result.kind === "deny") {',
        '             __zenithDispatchRouteEvent("route:deny", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, result });',
        '             console.warn("[Zenith] Route denied:", result.message);',
        '             if (result.status === 401 && policy.deny401RedirectToLogin !== false) {',
        '                 const loginPath = policy.defaultLoginPath || "/login";',
        '                 window._zenith_is_popstate_nav = false;',
        '                 window.location.assign(loginPath + "?next=" + encodeURIComponent(targetUrl.pathname + targetUrl.search + targetUrl.hash));',
        '                 return;',
        '             }',
        '             if (result.status === 403 && (policy.onDeny === "navigate" || policy.onDeny === "render403" || policy.forbiddenPath)) {',
        '                 window._zenith_is_popstate_nav = false;',
        '                 window.location.assign(policy.forbiddenPath || "/403");',
        '                 return;',
        '             }',
        '             if (policy.onDeny === "redirect") {',
        '                 window._zenith_is_popstate_nav = false;',
        '                 window.location.assign(policy.defaultLoginPath || "/login");',
        '                 return;',
        '             }',
        '             if (typeof policy.onDeny === "function") {',
        '                 policy.onDeny(result);',
        '                 window._zenith_is_popstate_nav = false;',
        '                 return;',
        '             }',
        '             window._zenith_is_popstate_nav = false;',
        '             history.back(); // Revert the popstate in history to align url bar with DOM',
        '             return; // No-flash block',
        '          }',
        '          onSuccess();',
        '        } else {',
        '          window._zenith_is_popstate_nav = false;',
        '          window.location.assign(targetUrl.href);',
        '        }',
        '      }).catch(function(e) {',
        '          __zenithDispatchRouteEvent("route-check:error", { to: targetUrl, from: new URL(window.location.href), routeId: resolved.route, error: e });',
        '          console.error("[Zenith Router] fallback route-check failed", e);',
        '          window._zenith_is_popstate_nav = false;',
        '          window.location.assign(targetUrl.href);',
        '      });',
        '    }',
        '',
        '    popstateEvaluateGuard(nextPath, url, function() {',
        '      navigate(nextPath, url).catch(function (error) {',
        "        console.error('[Zenith Router] popstate navigation failed', error);",
        '        window.location.assign(url.href);',
        '      });',
        '      window._zenith_is_popstate_nav = false;',
        '    });',
        '  });',
        '',
        '',
        '  navigate(window.location.pathname, null).catch(function (error) {',
        "    console.error('[Zenith Router] initial navigation failed', error);",
        '  });',
        '}',
        '',
        "if (document.readyState === 'loading') {",
        "  document.addEventListener('DOMContentLoaded', start, { once: true });",
        '} else {',
        '  start();',
        '}'
    ];

    return `${lines.join('\n')}\n`;
}
