export const sponsorsCollection = {
  name: "sponsors",
  label: "Sponsorship",
  path: "site/src/content/sponsors",
  format: "json",
  fields: [
    {
      type: "string",
      name: "kind",
      label: "Record type",
      required: true,
      options: ["invitation", "sponsor"],
    },
    { type: "string", name: "name", label: "Record name", isTitle: true, required: true },
    { type: "string", name: "url", label: "Sponsor URL" },
    {
      type: "object",
      name: "logo",
      label: "Logo",
      fields: [
        { type: "image", name: "src", label: "Image" },
        { type: "number", name: "width", label: "Width" },
        { type: "number", name: "height", label: "Height" },
        { type: "string", name: "alt", label: "Alt text" },
        { type: "string", name: "focalPosition", label: "Focal position" },
      ],
    },
    { type: "string", name: "title", label: "Section title" },
    { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
    { type: "string", name: "recognitionText", label: "Recognition text", ui: { component: "textarea" } },
    { type: "string", name: "ctaLabel", label: "CTA label" },
    { type: "string", name: "ctaUrl", label: "CTA URL" },
    { type: "string", name: "supportingStatements", label: "Supporting statements", list: true },
    { type: "boolean", name: "active", label: "Active" },
    { type: "boolean", name: "featured", label: "Featured" },
    { type: "datetime", name: "startsAt", label: "Starts at" },
    { type: "datetime", name: "endsAt", label: "Ends at" },
  ],
};
