use crate::codegen::generate;
use crate::parser::Parser;
use crate::script::{
    extract_script_blocks, ComponentInstanceBinding, ComponentScriptAsset, ExtractedStyleBlock,
    HoistedOutput, HoistedStateBinding,
};
use crate::transform::{
    transform, EventBinding, MarkerBinding, MarkerKind, RefBinding, TransformWarning,
};
use std::collections::BTreeMap;

pub const IR_VERSION: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct CompileOptions {
    pub embedded_markup_expressions: bool,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct HoistedPayload {
    pub imports: Vec<String>,
    pub declarations: Vec<String>,
    pub functions: Vec<String>,
    pub signals: Vec<String>,
    pub state: Vec<HoistedState>,
    pub code: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct HoistedState {
    pub key: String,
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ComponentScriptPayload {
    pub hoist_id: String,
    pub factory: String,
    pub imports: Vec<String>,
    pub code: String,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ComponentInstancePayload {
    pub instance: String,
    pub hoist_id: String,
    pub selector: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SignalPayload {
    pub id: usize,
    pub kind: String,
    pub state_index: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ExpressionBindingPayload {
    pub marker_index: usize,
    pub signal_index: Option<usize>,
    pub state_index: Option<usize>,
    pub component_instance: Option<String>,
    pub component_binding: Option<String>,
    pub literal: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MarkerPayload {
    pub index: usize,
    pub kind: String,
    pub selector: String,
    pub attr: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct EventPayload {
    pub index: usize,
    pub event: String,
    pub selector: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RefBindingPayload {
    pub index: usize,
    pub identifier: String,
    pub selector: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct GraphNodePayload {
    pub id: String,
    pub hoist_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct CompileWarning {
    pub code: String,
    pub message: String,
    pub line: usize,
    pub column: usize,
}

/// The sealed public API for the bundler.
/// This is the ONLY interface the bundler sees.
/// The bundler must NOT reach into AST, modify nodes, or influence indexing.
#[derive(Debug, Clone, PartialEq)]
pub struct CompilerOutput {
    /// Versioned IR envelope contract.
    pub ir_version: u32,
    /// Deterministic graph hash for the page/module graph.
    pub graph_hash: String,
    /// Deterministic graph edges in canonical order.
    pub graph_edges: Vec<String>,
    /// Deterministic graph nodes in canonical order.
    pub graph_nodes: Vec<GraphNodePayload>,
    /// The compiled HTML template string.
    pub html: String,
    /// The expression table — ordered, deterministic, left-to-right depth-first.
    pub expressions: Vec<String>,
    /// Raw import metadata emitted by the compiler.
    pub imports: Vec<String>,
    /// Optional server-side script payload.
    pub server_script: Option<String>,
    /// Whether prerender is enabled for this output.
    pub prerender: bool,
    /// Optional serialized SSR data payload.
    pub ssr_data: Option<String>,
    /// Hoisted declarations from component/page script blocks.
    pub hoisted: HoistedPayload,
    /// Deduplicated component script modules keyed by stable hoist id.
    pub components_scripts: BTreeMap<String, ComponentScriptPayload>,
    /// Per-page component instance bindings in deterministic traversal order.
    pub component_instances: Vec<ComponentInstancePayload>,
    /// Explicit signal table consumed by runtime without name lookup.
    pub signals: Vec<SignalPayload>,
    /// Explicit expression table consumed by runtime without identifier lookup.
    pub expression_bindings: Vec<ExpressionBindingPayload>,
    /// Explicit marker bindings generated by compiler.
    pub marker_bindings: Vec<MarkerPayload>,
    /// Explicit event bindings generated by compiler.
    pub event_bindings: Vec<EventPayload>,
    /// Explicit ref bindings generated by compiler.
    pub ref_bindings: Vec<RefBindingPayload>,
    /// Compiler-emitted style blocks in deterministic order.
    pub style_blocks: Vec<ExtractedStyleBlock>,
}

impl Default for CompilerOutput {
    fn default() -> Self {
        Self {
            ir_version: IR_VERSION,
            graph_hash: String::new(),
            graph_edges: Vec::new(),
            graph_nodes: Vec::new(),
            html: String::new(),
            expressions: Vec::new(),
            imports: Vec::new(),
            server_script: None,
            prerender: false,
            ssr_data: None,
            hoisted: HoistedPayload::default(),
            components_scripts: BTreeMap::new(),
            component_instances: Vec::new(),
            signals: Vec::new(),
            expression_bindings: Vec::new(),
            marker_bindings: Vec::new(),
            event_bindings: Vec::new(),
            ref_bindings: Vec::new(),
            style_blocks: Vec::new(),
        }
    }
}

/// Compile a template into the structured bundler output.
/// This is the primary entry point for programmatic use.
pub fn compile_structured(input: &str) -> Result<CompilerOutput, String> {
    compile_structured_with_source(input, "<inline>")
}

pub fn compile_structured_with_source(
    input: &str,
    source_path: &str,
) -> Result<CompilerOutput, String> {
    compile_structured_with_source_options(input, source_path, CompileOptions::default())
}

pub fn compile_structured_with_source_options(
    input: &str,
    source_path: &str,
    options: CompileOptions,
) -> Result<CompilerOutput, String> {
    compile_structured_with_source_options_and_warnings(input, source_path, options)
        .map(|(output, _warnings)| output)
}

pub fn compile_structured_with_source_options_and_warnings(
    input: &str,
    source_path: &str,
    options: CompileOptions,
) -> Result<(CompilerOutput, Vec<CompileWarning>), String> {
    let result = std::panic::catch_unwind(|| {
        let (
            ast,
            expressions,
            hoisted,
            component_scripts,
            component_instances,
            markers,
            events,
            ref_bindings,
            warnings,
        ) = compile_internal_result(input, source_path, options)?;
        let html = crate::codegen::generate_html(&ast);
        let signals = map_signals(&hoisted);
        let expression_bindings = map_expression_bindings(&expressions, &hoisted, &signals);

        let output = CompilerOutput {
            ir_version: IR_VERSION,
            graph_hash: String::new(),
            graph_edges: Vec::new(),
            graph_nodes: Vec::new(),
            html,
            expressions,
            imports: Vec::new(),
            server_script: None,
            prerender: false,
            ssr_data: None,
            hoisted: map_hoisted(hoisted),
            components_scripts: map_component_scripts(component_scripts),
            component_instances: map_component_instances(component_instances),
            signals,
            expression_bindings,
            marker_bindings: map_markers(markers),
            event_bindings: map_events(events),
            ref_bindings: map_ref_bindings(ref_bindings),
            style_blocks: Vec::new(),
        };

        Ok((output, map_warnings(warnings)))
    });

    match result {
        Ok(inner) => inner,
        Err(payload) => Err(panic_payload_to_string(payload)),
    }
}

#[deprecated(note = "Use compile_structured_with_source instead.")]
pub fn compile_structured_with_source_result(
    input: &str,
    source_path: &str,
) -> Result<CompilerOutput, String> {
    compile_structured_with_source(input, source_path)
}

#[deprecated(
    note = "Unchecked API may panic on compiler errors. Use compile_structured_with_source instead."
)]
pub fn compile_structured_with_source_unchecked(input: &str, source_path: &str) -> CompilerOutput {
    compile_structured_with_source(input, source_path)
        .unwrap_or_else(|message| panic!("{}", message))
}

/// Compile a template into a full TypeScript module string.
/// Used by the CLI and for human-readable output.
pub fn compile(input: &str) -> Result<String, String> {
    let result = std::panic::catch_unwind(|| {
        let options = CompileOptions::default();
        let (
            ast,
            expressions,
            _hoisted,
            _component_scripts,
            _component_instances,
            _markers,
            _events,
            _ref_bindings,
            _warnings,
        ) = compile_internal_result(input, "<inline>", options)?;
        Ok(generate(ast, expressions))
    });

    match result {
        Ok(inner) => inner,
        Err(payload) => Err(panic_payload_to_string(payload)),
    }
}

#[deprecated(note = "Use compile instead.")]
pub fn compile_result(input: &str) -> Result<String, String> {
    compile(input)
}

#[deprecated(note = "Unchecked API may panic on compiler errors. Use compile instead.")]
pub fn compile_unchecked(input: &str) -> String {
    compile(input).unwrap_or_else(|message| panic!("{}", message))
}

fn compile_internal_result(
    input: &str,
    source_path: &str,
    options: CompileOptions,
) -> Result<
    (
        crate::ast::Node,
        Vec<String>,
        HoistedOutput,
        BTreeMap<String, ComponentScriptAsset>,
        Vec<ComponentInstanceBinding>,
        Vec<MarkerBinding>,
        Vec<EventBinding>,
        Vec<RefBinding>,
        Vec<TransformWarning>,
    ),
    String,
> {
    let (preprocessed, scripts) =
        extract_script_blocks(input, source_path).map_err(|err| err.message)?;
    let normalized = strip_html_comments(&preprocessed);

    let mut parser = Parser::new_with_options(
        &normalized,
        options.embedded_markup_expressions,
    );
    let ast = parser.parse();
    Ok(transform(ast, &scripts))
}

fn panic_payload_to_string(payload: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = payload.downcast_ref::<String>() {
        return s.clone();
    }
    if let Some(s) = payload.downcast_ref::<&str>() {
        return s.to_string();
    }
    "Compiler failed with non-string panic payload".to_string()
}

fn strip_html_comments(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut cursor = 0usize;

    while let Some(rel_start) = input[cursor..].find("<!--") {
        let start = cursor + rel_start;
        out.push_str(&input[cursor..start]);

        let after_open = start + 4;
        if let Some(rel_end) = input[after_open..].find("-->") {
            cursor = after_open + rel_end + 3;
        } else {
            // Unterminated comment: treat the remainder as comment and stop.
            return out;
        }
    }

    out.push_str(&input[cursor..]);
    out
}

fn map_hoisted(output: HoistedOutput) -> HoistedPayload {
    HoistedPayload {
        imports: output.imports,
        declarations: output.declarations,
        functions: output.functions,
        signals: output.signals,
        state: output
            .state_bindings
            .into_iter()
            .map(|binding: HoistedStateBinding| HoistedState {
                key: binding.key,
                value: binding.value,
            })
            .collect(),
        code: output.code,
    }
}

fn map_component_scripts(
    scripts: BTreeMap<String, ComponentScriptAsset>,
) -> BTreeMap<String, ComponentScriptPayload> {
    let mut out = BTreeMap::new();
    for (key, script) in scripts {
        out.insert(
            key,
            ComponentScriptPayload {
                hoist_id: script.hoist_id,
                factory: script.factory,
                imports: script.imports,
                code: script.code,
            },
        );
    }
    out
}

fn map_component_instances(
    instances: Vec<ComponentInstanceBinding>,
) -> Vec<ComponentInstancePayload> {
    instances
        .into_iter()
        .map(|instance| ComponentInstancePayload {
            instance: instance.instance,
            hoist_id: instance.hoist_id,
            selector: instance.selector,
        })
        .collect()
}

fn map_signals(hoisted: &HoistedOutput) -> Vec<SignalPayload> {
    let state_index_by_key = hoisted
        .state_bindings
        .iter()
        .enumerate()
        .map(|(idx, item)| (item.key.clone(), idx))
        .collect::<BTreeMap<_, _>>();

    let mut signals = Vec::new();
    for key in &hoisted.signals {
        let Some(state_index) = state_index_by_key.get(key) else {
            continue;
        };
        signals.push(SignalPayload {
            id: signals.len(),
            kind: "signal".to_string(),
            state_index: *state_index,
        });
    }
    signals
}

fn map_expression_bindings(
    expressions: &[String],
    hoisted: &HoistedOutput,
    signals: &[SignalPayload],
) -> Vec<ExpressionBindingPayload> {
    let state_index_by_key = hoisted
        .state_bindings
        .iter()
        .enumerate()
        .map(|(idx, item)| (item.key.clone(), idx))
        .collect::<BTreeMap<_, _>>();

    let signal_index_by_state = signals
        .iter()
        .map(|signal| (signal.state_index, signal.id))
        .collect::<BTreeMap<_, _>>();

    expressions
        .iter()
        .enumerate()
        .map(|(index, expr)| {
            if let Some(state_index) = state_index_by_key.get(expr) {
                return ExpressionBindingPayload {
                    marker_index: index,
                    signal_index: signal_index_by_state.get(state_index).copied(),
                    state_index: Some(*state_index),
                    component_instance: None,
                    component_binding: None,
                    literal: None,
                };
            }

            if let Some((instance, binding)) = parse_component_binding(expr) {
                return ExpressionBindingPayload {
                    marker_index: index,
                    signal_index: None,
                    state_index: None,
                    component_instance: Some(instance),
                    component_binding: Some(binding),
                    literal: None,
                };
            }

            ExpressionBindingPayload {
                marker_index: index,
                signal_index: None,
                state_index: None,
                component_instance: None,
                component_binding: None,
                literal: Some(expr.clone()),
            }
        })
        .collect()
}

fn parse_component_binding(expr: &str) -> Option<(String, String)> {
    let mut segments = expr.split('.');
    let instance = segments.next()?;
    let binding = segments.next()?;
    if segments.next().is_some() {
        return None;
    }
    if !instance.starts_with('c') || instance.len() < 2 {
        return None;
    }
    if !instance[1..].chars().all(|ch| ch.is_ascii_digit()) {
        return None;
    }
    if binding.is_empty()
        || !binding
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '$')
    {
        return None;
    }
    Some((instance.to_string(), binding.to_string()))
}

fn map_markers(markers: Vec<MarkerBinding>) -> Vec<MarkerPayload> {
    markers
        .into_iter()
        .map(|marker| MarkerPayload {
            index: marker.index,
            kind: match marker.kind {
                MarkerKind::Text => "text",
                MarkerKind::Attr => "attr",
                MarkerKind::Event => "event",
            }
            .to_string(),
            selector: marker.selector,
            attr: marker.attr,
        })
        .collect()
}

fn map_events(events: Vec<EventBinding>) -> Vec<EventPayload> {
    events
        .into_iter()
        .map(|event| EventPayload {
            index: event.index,
            event: event.event,
            selector: event.selector,
        })
        .collect()
}

fn map_ref_bindings(bindings: Vec<RefBinding>) -> Vec<RefBindingPayload> {
    bindings
        .into_iter()
        .map(|binding| RefBindingPayload {
            index: binding.index,
            identifier: binding.identifier,
            selector: binding.selector,
        })
        .collect()
}

fn map_warnings(warnings: Vec<TransformWarning>) -> Vec<CompileWarning> {
    warnings
        .into_iter()
        .map(|warning| CompileWarning {
            code: warning.code,
            message: warning.message,
            line: warning.line,
            column: warning.column,
        })
        .collect()
}
