name: ci

on:
  pull_request:
    branches:
      - train
      - master
      - beta
  push:
    branches:
      - beta
      - train
      - master

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    secrets: inherit
