import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createNetlifyBasePathAssetRules, createNetlifyRewriteRules } from './route-rules.js';
import type { AdapterDriver, BuildManifest } from './adapter-types.js';

function createRedirectsFile(manifest: BuildManifest) {
    const lines = [
        '# Generated by Zenith netlify-static adapter',
        ...createNetlifyBasePathAssetRules(manifest.base_path)
    ];
    const seen = new Set<string>();

    for (const route of manifest.routes) {
        for (const line of createNetlifyRewriteRules(route, manifest.base_path)) {
            if (seen.has(line)) {
                continue;
            }
            seen.add(line);
            lines.push(line);
        }
    }

    return `${lines.join('\n')}\n`;
}

export const netlifyStaticAdapter: AdapterDriver = {
    name: 'netlify-static',
    validateRoutes(manifest) {
        const serverRoutes = manifest.filter((entry) => entry.render_mode === 'server');
        if (serverRoutes.length === 0) {
            return;
        }

        const first = serverRoutes[0];
        throw new Error(
            `[Zenith:Build] target "netlify-static" cannot emit server-rendered routes. ` +
            `Route "${first.path}" (${first.file}) requires render_mode="server".`
        );
    },
    async adapt(options) {
        const staticDir = join(options.coreOutput, 'static');
        await rm(options.outDir, { recursive: true, force: true });
        await mkdir(options.outDir, { recursive: true });
        await cp(staticDir, options.outDir, { recursive: true, force: true });
        await writeFile(
            join(options.outDir, '_redirects'),
            createRedirectsFile(options.manifest),
            'utf8'
        );
    }
};
