import type { BuildManifest } from './adapter-types.js';
import type { HostedServerManifestRoute } from './hosted-adapter-context.js';

type HostedRouteCheckExport = 'vercel' | 'netlify';

interface HostedRouteCheckSourceOptions {
    buildManifest: BuildManifest;
    pageServerRoutes: HostedServerManifestRoute[];
    runtimeBasePath: string;
    routeModuleBaseSegments: string[];
    exportKind: HostedRouteCheckExport;
}

function sourceJoinSegments(segments: string[]): string {
    return segments.map((segment) => JSON.stringify(segment)).join(', ');
}

function createHostedRouteCheckExport(kind: HostedRouteCheckExport): string {
    if (kind === 'vercel') {
        return [
            'export default {',
            '  async fetch(request) {',
            '    return handleRouteCheck(request);',
            '  }',
            '};'
        ].join('\n');
    }
    return [
        'export default async function(request) {',
        '  return handleRouteCheck(request);',
        '}'
    ].join('\n');
}

export function createHostedRouteCheckSource(options: HostedRouteCheckSourceOptions): string {
    const {
        buildManifest,
        pageServerRoutes,
        runtimeBasePath,
        routeModuleBaseSegments,
        exportKind
    } = options;
    const routeModuleBase = sourceJoinSegments(routeModuleBaseSegments);
    const routeModuleJoinPrefix = routeModuleBase.length > 0 ? `${routeModuleBase}, ` : '';
    return [
        "import { fileURLToPath } from 'node:url';",
        "import { dirname, join } from 'node:path';",
        `import { appLocalRedirectLocation, normalizeBasePath, stripBasePath } from '${runtimeBasePath}/base-path.js';`,
        `import { executeRouteRequest } from '${runtimeBasePath}/runtime/route-render.js';`,
        `import { defaultRouteDenyMessage, logServerException, sanitizeRouteResult } from '${runtimeBasePath}/server-error.js';`,
        '',
        'const __dirname = dirname(fileURLToPath(import.meta.url));',
        `const basePath = normalizeBasePath(${JSON.stringify(buildManifest.base_path || '/')});`,
        `const buildRoutes = ${JSON.stringify(buildManifest.routes || [], null, 2)};`,
        `const pageServerRoutes = ${JSON.stringify(pageServerRoutes, null, 2)};`,
        '',
        'function jsonResponse(status, body, headers = {}) {',
        '  return new Response(JSON.stringify(body), {',
        '    status,',
        '    headers: {',
        "      'Content-Type': 'application/json',",
        '      ...headers',
        '    }',
        '  });',
        '}',
        '',
        'function splitPath(pathname) {',
        "  return String(pathname || '').split('/').filter(Boolean);",
        '}',
        '',
        'function compareRouteSpecificity(a, b) {',
        "  if (a === '/' && b !== '/') return -1;",
        "  if (b === '/' && a !== '/') return 1;",
        '  const aSegs = splitPath(a);',
        '  const bSegs = splitPath(b);',
        '  const aClass = routeClass(aSegs);',
        '  const bClass = routeClass(bSegs);',
        '  if (aClass !== bClass) return bClass - aClass;',
        '  const max = Math.min(aSegs.length, bSegs.length);',
        '  for (let i = 0; i < max; i += 1) {',
        '    const aWeight = segmentWeight(aSegs[i]);',
        '    const bWeight = segmentWeight(bSegs[i]);',
        '    if (aWeight !== bWeight) return bWeight - aWeight;',
        '  }',
        '  if (aSegs.length !== bSegs.length) return bSegs.length - aSegs.length;',
        '  return String(a || "").localeCompare(String(b || ""));',
        '}',
        '',
        'function routeClass(segments) {',
        '  let hasParam = false;',
        '  let hasCatchAll = false;',
        '  for (const segment of segments) {',
        "    if (segment.startsWith('*')) hasCatchAll = true;",
        "    else if (segment.startsWith(':')) hasParam = true;",
        '  }',
        '  if (!hasParam && !hasCatchAll) return 3;',
        '  if (hasCatchAll) return 1;',
        '  return 2;',
        '}',
        '',
        'function segmentWeight(segment) {',
        '  if (!segment) return 0;',
        "  if (segment.startsWith('*')) return 1;",
        "  if (segment.startsWith(':')) return 2;",
        '  return 3;',
        '}',
        '',
        'function normalizeCatchAll(segments) {',
        "  return segments.filter(Boolean).join('/');",
        '}',
        '',
        'function matchRoute(pathname, routes) {',
        '  const target = splitPath(pathname);',
        '  const ordered = [...routes].sort((left, right) => compareRouteSpecificity(left.path, right.path));',
        '  for (const entry of ordered) {',
        '    const pattern = splitPath(entry.path);',
        '    const params = Object.create(null);',
        '    let patternIndex = 0;',
        '    let valueIndex = 0;',
        '    let matched = true;',
        '    while (patternIndex < pattern.length) {',
        '      const segment = pattern[patternIndex];',
        "      if (segment.startsWith('*')) {",
        "        const optionalCatchAll = segment.endsWith('?');",
        '        const key = optionalCatchAll ? segment.slice(1, -1) : segment.slice(1);',
        '        if (patternIndex !== pattern.length - 1) {',
        '          matched = false;',
        '          break;',
        '        }',
        '        const rest = target.slice(valueIndex);',
        '        const rootRequiredCatchAll = !optionalCatchAll && pattern.length === 1;',
        '        if (rest.length === 0 && !optionalCatchAll && !rootRequiredCatchAll) {',
        '          matched = false;',
        '          break;',
        '        }',
        '        params[key] = normalizeCatchAll(rest);',
        '        valueIndex = target.length;',
        '        patternIndex = pattern.length;',
        '        break;',
        '      }',
        '      if (valueIndex >= target.length) {',
        '        matched = false;',
        '        break;',
        '      }',
        '      const value = target[valueIndex];',
        "      if (segment.startsWith(':')) params[segment.slice(1)] = value;",
        '      else if (segment !== value) {',
        '        matched = false;',
        '        break;',
        '      }',
        '      patternIndex += 1;',
        '      valueIndex += 1;',
        '    }',
        '    if (!matched) continue;',
        '    if (valueIndex !== target.length || patternIndex !== pattern.length) continue;',
        '    return { route: entry, params: { ...params } };',
        '  }',
        '  return null;',
        '}',
        '',
        'function resolveRequestRoute(reqUrl, routes) {',
        "  const url = reqUrl instanceof URL ? reqUrl : new URL(String(reqUrl), 'http://localhost');",
        '  const matched = matchRoute(url.pathname, routes);',
        '  if (!matched) return { matched: false, route: null, params: {} };',
        '  return { matched: true, route: matched.route, params: matched.params };',
        '}',
        '',
        'function normalizeRouteCheckResult(result, targetUrl) {',
        "  if (!result || result.kind !== 'redirect') return result;",
        '  const location = appLocalRedirectLocation(result.location, basePath);',
        "  if (location.includes('://') || location.startsWith('//')) {",
        '    try {',
        '      const redirectUrl = new URL(location);',
        '      if (redirectUrl.origin !== targetUrl.origin) {',
        "        return { ...result, location: appLocalRedirectLocation('/', basePath) };",
        '      }',
        '    } catch {',
        "      return { ...result, location: appLocalRedirectLocation('/', basePath) };",
        '    }',
        '  }',
        '  return { ...result, location };',
        '}',
        '',
        'async function handleRouteCheck(request) {',
        "  if (request.headers.get('x-zenith-route-check') !== '1') {",
        "    return jsonResponse(403, { error: 'forbidden', message: 'invalid request context' });",
        '  }',
        '',
        '  const url = new URL(request.url);',
        "  const targetPath = String(url.searchParams.get('path') || '/');",
        "  if (targetPath.includes('://') || targetPath.startsWith('//') || /[\\r\\n]/.test(targetPath)) {",
        "    return jsonResponse(400, { error: 'invalid_path_format' });",
        '  }',
        '',
        '  const targetUrl = new URL(targetPath, url.origin);',
        '  if (targetUrl.origin !== url.origin) {',
        "    return jsonResponse(400, { error: 'external_route_evaluation_forbidden' });",
        '  }',
        '',
        '  const canonicalPath = stripBasePath(targetUrl.pathname, basePath);',
        '  if (canonicalPath === null) {',
        "    return jsonResponse(404, { error: 'route_not_found' });",
        '  }',
        '',
        '  const canonicalTargetUrl = new URL(targetUrl.toString());',
        '  canonicalTargetUrl.pathname = canonicalPath;',
        '  const buildResolved = resolveRequestRoute(canonicalTargetUrl, buildRoutes);',
        '  if (!buildResolved.matched || !buildResolved.route) {',
        "    return jsonResponse(404, { error: 'route_not_found' });",
        '  }',
        '',
        "  let result = { kind: 'allow' };",
        "  let routeId = buildResolved.route.path || '';",
        '  const serverResolved = resolveRequestRoute(canonicalTargetUrl, pageServerRoutes);',
        '  if (serverResolved.matched && serverResolved.route) {',
        '    routeId = serverResolved.route.route_id || serverResolved.route.name || serverResolved.route.path || routeId;',
        '    try {',
        '      const routeRequest = new Request(targetUrl.toString(), {',
        "        method: request.method || 'GET',",
        '        headers: request.headers',
        '      });',
        '      const execution = await executeRouteRequest({',
        '        request: routeRequest,',
        '        route: serverResolved.route,',
        '        params: serverResolved.params,',
        `        routeModulePath: join(__dirname, ${routeModuleJoinPrefix}serverResolved.route.name, 'route', 'entry.js'),`,
        '        guardOnly: true',
        '      });',
        '      result = normalizeRouteCheckResult(execution.result, targetUrl);',
        '    } catch (error) {',
        "      logServerException('hosted route-check failed', error);",
        '      result = {',
        "        kind: 'deny',",
        '        status: 500,',
        '        message: defaultRouteDenyMessage(500)',
        '      };',
        '    }',
        '  }',
        '',
        '  return jsonResponse(200, {',
        '    result: sanitizeRouteResult(result),',
        '    routeId,',
        '    to: targetUrl.toString()',
        '  }, {',
        "    'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',",
        "    Pragma: 'no-cache',",
        "    Expires: '0',",
        "    Vary: 'Cookie'",
        '  });',
        '}',
        '',
        createHostedRouteCheckExport(exportKind),
        ''
    ].join('\n');
}
